// Generated by CoffeeScript 1.3.3
(function () {
    var  youTubeVideo;

    youTubeVideo = function (str) {
        var videoClass = str;
        $('.' + videoClass).each(function () {
            var id = $(this).attr('video-id');
            if ($('img', $(this)).length > 0) {
                $(this).find('img').attr('src', 'http://img.youtube.com/vi/' + id + '/maxresdefault.jpg');
                alert('1');
            }
            else {
                var img = $('<img></img>');
                img.attr('src', 'http://img.youtube.com/vi/' + id + '/maxresdefault.jpg');
                img.appendTo($(this));
            }
            

            $(this).on('click', function () {
                if (!App.player) {
                    var tag = document.createElement('script');

                    tag.src = "//www.youtube.com/iframe_api";
                    $('script').each(function () {
                        if ($(this).src == tag.src) return false;
                    });
                    var firstScriptTag = document.getElementsByTagName('script')[0];
                    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

                    var id = $(this).attr('video-id');
                    window.onYouTubeIframeAPIReady = function () {
                        createPlayer(id);
                    }

                } else {
                    var id = $(this).attr('video-id');
                    createPlayer(id);
                }
                function createPlayer(id) {
                    var video = $('<div></div>').addClass('yt-player').addClass('hiden').hide();
                    video.html('<div id="player"></div><button type="button" title="Menu" class="removeBox"></button>');
                    video.appendTo('body');

                    App.player = new YT.Player('player', {
                        height: '100%',
                        width: '100%',
                        videoId: id,
                        playerVars: {
                            'rel': 0,
                            'showinfo': 0,
                            'enablejsapi': 1,
                            'autoplay': 0
                        },
                        events: {
                            'onReady': onPlayerReady
                        }
                    });
                    function onPlayerReady(event) {
                        var contener = $(event.target.a).parent();
                        if (contener.hasClass('hiden')) {
                            showVideo();
                        }

                    }
                }
                function showVideo(id) {
                    var wideoWraper = $('.yt-player');
                    var videoWidth = $('.main-content').width();
                    var videoHeight = videoWidth * (2 / 4);
                    var bg = $('<div></div>').addClass('popup-wraper');

                    wideoWraper.css({
                        width: videoWidth,
                        height: videoHeight
                    });

                    var bg = $('<div></div>').addClass('popup-wraper');
                    bg.appendTo($('body'));
                    wideoWraper.dialog({
                        width: videoWidth,
                        height: videoHeight,
                        close: function (event, ui) {
                            $('.popup-wraper').remove();
                            $(this).dialog("destroy");
                            wideoWraper.remove();
                        }
                    });
                }
            });
        });
        
    };


}).call(this);